### ISSUE TITLE
check fork blocknum >= eip1559 hard fork block

### ISSUE THREAD

**Issue by bb111189** [Layr-Labs/devkit-cli#182]
```yaml
  chains:
    l1:
      chain_id: 31337
      rpc_url: "http://localhost:8545"
      fork:
        block: 22475020
        url: ""
        block_time: 3
```

If blocknum is zero instead of 22475020, eip1559 gas estimation issue occurs

```bash
Script ran successfully.

== Logs ==
  Deployer address: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  TaskMailbox deployed to: 0x5FbDB2315678afecb367f032d93F642f64180aa3

## Setting up 1 EVM.
==========================
Simulated On-chain Traces:

  [3046021] → new TaskMailbox@0x5FbDB2315678afecb367f032d93F642f64180aa3
    └─ ← [Return] 15103 bytes of code

Error: Failed to get EIP-1559 fees; unsupported feature: eip1559
```
